# Overrides immediate opcodes in bank 80 to be pointers
- { addr: 0x808980, db: 0x80 }
- { addr: 0x809B56, db: 0x80 }
- { addr: 0x809B5E, db: 0x80 }

# Sets the reset vectors to pointers
- { addr: [0x80FFE0, 0x80FFFF], db: 0x80 }
