#
# Overrides the automatic import "guesses" with correct data for any given address
#
# Address can either be a single address, or a range (inclusive)
#
# Can also specify a data type for data in a range (for labling)
#
# db is optional, and will be set to the same bank as the address if not defined for data, or the "guessed" db in case of code
